.TH install_fromiso_in_USB "8" "12th October 2007" "" ""
.SH NAME
\fBinstall_fromiso_in_USB\fR \- installs a live-CD iso build with the fll\-tools
as a fromiso into a USB pen
.SH SYNOPSIS
\fBinstall_fromiso_in_USB\fR \fI<options>\fR
.SH DESCRIPTION
installs a \fBF.U.L.L.S.T.O.R.Y.\fR iso-image on a USB-pen, makes the pen bootable and 
writes the needed grub files.
.PP
\fBinstall_fromiso_in_USB\fR creates a partition over the USB-device, installs
grub and copies the iso into it. When running from the live CD it copies his contents
into the US device.
.PP
\fBinstall_fromiso_in_USB\fR is intended to be called by the \fBinstall-usb-gui\fR programm 
but can also be called directly. 
.PP
.SH OPTIONS
.TP
\fB\-h|\-\-help\fR
print help screen
.TP
\fB\-D|\-\-device\fR \fI<device>\fR
name of device where to install the \"fromiso\"
.TP
\fB\-I|\-\-iso\fR \fI<iso_file>\fR
name of the iso image to be installed
.TP
\fB\-L|\-\-label\fR \fI<name>\fR
label name to be used for the created partition
.TP
\fB\-l|\-\-lang\fR \fI<name>\fR
default system language/locale
.TP
\fB\-p|\-\-persist\fR
use device as persistent storage device
.TP
\fB\-T|\-\-toram\fR
add toram boot option as default
.TP
\fB\-t|\-\-test\fR
do not copy the iso image
.TP
\fB\-d|\-\-debug\fR
debug sh code execution
.PP
.SH AUTHOR
This manual page was written by Joaquim Boura <x-un-i@sidux.com> 
